name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feat/*

    paths-ignore:
      - README.md

jobs:
  # 🧩 1️⃣ Install Dependencies
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
        working-directory: ./src/backend
        name: Install dependencies

  # ☁️ 2️⃣ Deploy Infrastructure
  deploy-infra:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - uses: actions/checkout@v4

      # Authenticate to Azure
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy the Bicep template
      - name: Deploy Infrastructure with Bicep
        uses: azure/cli@v2
        with:
          inlineScript: |
            echo "Deploying infrastructure..."
            az deployment group create \
              --resource-group rg-bicep-tutorial \
              --template-file infra/main.bicep \
              --parameters @infra/parameters.json

  # 🔍 3️⃣ Validate Infra
  validate-infra:
    runs-on: ubuntu-latest
    needs: deploy-infra
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Validate Infrastructure
        uses: azure/cli@v2
        with:
          inlineScript: |
            echo "Validating infrastructure..."
            az deployment group validate \
              --resource-group rg-bicep-tutorial \
              --template-file infra/main.bicep \
              --parameters @infra/parameters.json

  # 🚀 4️⃣ Deploy Code
  deploy-code:
    runs-on: ubuntu-latest
    needs: validate-infra
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy app code
        run: |
          echo "Deploying app to environment..."
          # Replace 'my-app' with your actual web app name and ensure the source path is correct.
          az webapp deploy --resource-group rg-bicep-tutorial --name bicepTut-webapp-001 --src-path ./src/backend
          # az webapp deploy --resource-group rg-bicep-tutorial --name bicepTut-webapp-001 --src-path ./src/backend
